Inspecting ply files.

In [6]:
import open3d as o3d
import numpy as np

ply_file_path = "../data/chest/point_cloud.ply"
pcd = o3d.io.read_point_cloud(ply_file_path)

Inspecting basic properties.

In [13]:
print("Number of points:", len(pcd.points))
print("Point cloud attributes:", pcd)

Number of points: 320835
Point cloud attributes: PointCloud with 320835 points.
Number of points: 320835


Check colors

In [15]:
if pcd.has_colors():
    print("Colors are present.")
else:
    print(pcd.has_colors())

False


In [18]:
if pcd.has_normals():
    print("Normals are present.")

if pcd.has_normals():
    print("First 5 normals:")
    print(np.asarray(pcd.normals)[:5])

Normals are present.
First 5 normals:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Check first five points.

In [8]:
print("First 5 points:", np.asarray(pcd.points)[:5])

First 5 points: [[-72.02342224 -78.9037323  -42.25225067]
 [-71.88059998 -78.54916382 -49.74679565]
 [-72.203125   -78.91300964 -45.88044739]
 [-71.99843597 -78.97512054 -37.42993927]
 [-72.06144714 -78.808815   -48.00378036]]


In [9]:
o3d.visualization.draw_geometries([pcd])

In [12]:
!head ../data/chest/point_cloud.ply

ply
format binary_little_endian 1.0
element vertex 320835
property float x
property float y
property float z
property float nx
property float ny
property float nz
property float f_dc_0


Now I try to use the plyfile library

In [20]:
from plyfile import PlyData
ply_data = PlyData.read("../data/chest/chest.ply")

In [25]:
ply_data["vertex"].data

memmap([(-35.631207  , -38.61256  , -43.49974 , 0., 0., 0., -0.12382404, -0.12382404, -0.12382402, -0.01190309, -0.00544231, -0.01006818,  0.00716738,  0.01225713,  2.6871148e-03,  0.00201433, 0.01398715, -0.00388838,  0.00061164,  0.00395637, 0.00697033,  0.01024741, -0.01899934, -0.01926922, -0.01190309, -0.00544231, -0.01006818,  0.00716738,  0.01225713,  2.6871134e-03,  0.00201433, 0.01398716, -0.00388838,  0.00061164,  0.00395637, 0.00697033,  0.01024742, -0.01899934, -0.01926921, -0.01190309, -0.00544231, -0.01006818,  0.00716738,  0.01225713,  2.6871117e-03,  0.00201433, 0.01398715, -0.00388838,  0.00061164,  0.00395637, 0.00697033,  0.01024742, -0.01899935, -0.01926922, -3.7830327,  0.96478  ,  1.281627  ,  1.4373379, 0.79125744, -0.20042448,  0.09945221, -0.23870765),
        (-37.88008   , -34.239906 , -43.865192, 0., 0., 0., -0.08687986, -0.08687983, -0.08687978, -0.01589591,  0.0012634 , -0.00202498,  0.00539248,  0.01133898,  1.8098378e-03,  0.00209404, 0.01921603,  0.0001

In [26]:
print("First 5 opacities:")
print(ply_data["vertex"]["opacity"][:5])

First 5 opacities:
[-3.7830327 -3.8409314 -3.9179153 -3.924104  -3.9200857]


In [27]:
print("First 5 scales:")
print(ply_data["vertex"]["scale_0"][:5], ply_data["vertex"]["scale_1"][:5], ply_data["vertex"]["scale_2"][:5])

First 5 scales:
[0.96478   1.1852579 1.4255192 1.3501743 1.3299135] [1.281627   1.1102407  0.90606296 0.85667974 0.9959964 ] [1.4373379 1.2081807 0.9414592 1.1965191 1.0679004]
